config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :workouts do
    resources :exercises
  end

  root 'workouts#index'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
  validates :name, presence: true, length: { maximum: 25 }
  validates :sets, presence: true
  validates :reps, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :workouts
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :exercises, dependent: :destroy
  belongs_to :user

  validates :date,    presence: true
  validates :workout, presence: true, length: { maximum: 40 }
  validates :mood,    presence: true
  validates :length,  presence: true
  validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!

  def create
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps))

    redirect_to workout_path(@workout)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  before_action :require_user, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @workouts = current_user.workouts.all.order("created_at DESC")
    end
  end

  def show
  end

  def new
    @workout = current_user.workouts.build
  end

  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    @workout.destroy
    redirect_to root_path
  end

  private

  def workout_params
    params.require(:workout).permit(:date, :workout, :mood, :length)
  end

  def find_workout
    @workout = Workout.find(params[:id])
  end

  def require_user
    if current_user != @workout.user
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_form.html.haml
= simple_form_for([@workout, @workout.exercises.build]) do |f|
  = f.input :name, input_html: { class: "form-control" }
  = f.input :sets, input_html: { class: "form-control" }
  = f.input :reps, input_html: { class: "form-control" }
  %br/
  = link_to "Edit", edit_workout_path(@workout), class: "btn btn-warning"
  = f.button :submit
  = link_to "Delete", workout_path(@workout), method: :delete, class: "btn btn-danger"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Workout Log", root_path, class: "navbar-brand"

    #bs-example-navbar-collapse-1.collapse.navbar-collapse.nav.navbar-nav.navbar-right
      - if current_user
        = link_to "New Workout", new_workout_path, class: "navbar-link"
        = link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-link"
      - else
        = link_to "Log In", new_user_session_path, class: "navbar-link"
        |
        = link_to "Sign Up", new_user_registration_path, class: "navbar-link"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Workout Log
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
%body
  = render 'layouts/navigation.html.haml'
  .container
    - if notice
      .alert.alert-success.text-center= notice
    - if alert
      .alert.alert-danger.text-center= alert

    = yield

app/views/workouts/_form.html.haml
= simple_form_for(@workout, html: { class: 'form-horizontal' }) do |f|
  = f.input :date, label: "Date"
  = f.input :workout, label: "What are did you workout?", input_html: { class: "form-control" }
  = f.input :mood, label: "How were you feeling?", input_html: { class: "form-control" }
  = f.input :length, label: "How long was the workout?", input_html: { class: "form-control" }
  %br/
  = f.button :submit
  = link_to "Cancel", root_path, class: "btn btn-default"

app/views/workouts/edit.html.haml
.row
  .col-md-6.col-md-offset-3.text-center
    %h1 Edit Workout
    = render 'form'

app/views/workouts/index.html.haml
- if user_signed_in? && @workouts.count >= 1
  #index_workouts
    - @workouts.each do |workout|
      %h2= link_to workout.date.strftime("%A %B %d"), workout
      %h3
        %span Workout:
        = workout.workout
- elsif !user_signed_in?
  %h1.zero_workouts.text-center You need to #{ link_to "Login", new_user_session_path } or #{ link_to "Register", new_user_registration_path }.
- elsif @workouts.count == 0
  %h1.zero_workouts You have 0 workouts.

app/views/workouts/new.html.haml
.row
  .col-md-6.col-md-offset-3.text-center
    %h1 New Workout
    = render 'form'

app/views/workouts/show.html.haml
.row
  .col-md-6
    #workout
      %h2= @workout.date.strftime("%A, %d %B %Y, %H:%M")
      %h3
        %span Part of body:
        = @workout.workout
        %br/
        %span Mood:
        = @workout.mood
        %br/
        %span Length:
        = @workout.length


      .text-center
        %br/
        %h3 Add an exercise
        %br/
        = render "exercises/form"

  .col-md-6
    #exercises
      %h2.text-center Exercises
      %table.table.table-condensed.borderless
        %thead
          %tr
            %th Name
            %th Sets
            %th Reps
        %tbody
          - @workout.exercises.each do |exercise|
            %tr
              %td= exercise.name
              %td= exercise.sets
              %td= exercise.reps
